# Authorizer cert-manager Issuers + Certificates — Multi-Environment
# Covers: Self-Signed (dev), ACME/Let's Encrypt (staging/prod), Vault (enterprise)
# Apply: kubectl apply -f cert_manager_issuers.yaml

---
# ============================================================
# DEV TIER: Self-Signed CA (kind/minikube/k3s)
# ============================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-root
  labels:
    authorizer.io/tier: "1-dev"
spec:
  selfSigned: {}

---
# Root CA Certificate (self-signed)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authorizer-root-ca
  namespace: cert-manager
  labels:
    authorizer.io/tier: "1-dev"
spec:
  isCA: true
  commonName: "authorizer-root-ca"
  secretName: authorizer-root-ca-secret
  duration: 87600h    # 10 years for dev CA
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 384
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io

---
# CA-backed ClusterIssuer for dev workloads
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: authorizer-ca-issuer-dev
  labels:
    authorizer.io/tier: "1-dev"
spec:
  ca:
    secretName: authorizer-root-ca-secret

---
# ============================================================
# STAGING TIER: Let's Encrypt Staging (ACME HTTP01)
# ============================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    authorizer.io/tier: "2-staging"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: platform@company.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
        selector:
          matchLabels:
            acme-solver: http01

---
# ============================================================
# PRODUCTION TIER: Let's Encrypt Prod (ACME DNS01 via Route53)
# ============================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    authorizer.io/tier: "3-production"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: platform@company.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      # DNS01 for wildcard certs
      - dns01:
          route53:
            region: us-east-1
            hostedZoneID: Z1PA6795UKMFR9
            role: arn:aws:iam::123456789012:role/cert-manager-dns01-role
        selector:
          dnsZones:
            - "company.com"
      # HTTP01 for specific subdomains
      - http01:
          ingress:
            ingressClassName: nginx
        selector:
          matchLabels:
            acme-solver: http01-prod

---
# ============================================================
# ENTERPRISE TIER: HashiCorp Vault (internal PKI)
# ============================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-pki-issuer
  labels:
    authorizer.io/tier: "4-enterprise"
spec:
  vault:
    server: https://vault.company.com:8200
    path: pki/sign/kubernetes-cluster
    caBundle: <BASE64_VAULT_CA>
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager-role
        secretRef:
          name: cert-manager-vault-token
          key: token

---
# ============================================================
# SERVICE TLS CERTIFICATE — reusable template
# Replace: <NAMESPACE>, <APP_NAME>, <DOMAIN>
# ============================================================
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <APP_NAME>-tls
  namespace: <NAMESPACE>
  labels:
    app.kubernetes.io/name: <APP_NAME>
    authorizer.io/cert-type: "service-tls"
spec:
  secretName: <APP_NAME>-tls
  duration: 24h
  renewBefore: 8h
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  usages:
    - server auth
    - client auth    # Both server+client for mTLS
  subject:
    organizations:
      - company.com
  commonName: <APP_NAME>.<NAMESPACE>.svc.cluster.local
  dnsNames:
    - <APP_NAME>
    - <APP_NAME>.<NAMESPACE>
    - <APP_NAME>.<NAMESPACE>.svc
    - <APP_NAME>.<NAMESPACE>.svc.cluster.local
    - <DOMAIN>    # External domain if applicable
  issuerRef:
    name: authorizer-ca-issuer-dev    # Replace with tier-appropriate issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
# ============================================================
# INGRESS TLS CERTIFICATE (public-facing)
# ============================================================
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-wildcard-tls
  namespace: ingress-nginx
  labels:
    authorizer.io/cert-type: "ingress-wildcard"
spec:
  secretName: company-wildcard-tls
  duration: 2160h     # 90 days
  renewBefore: 720h   # Renew 30 days before expiry
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  dnsNames:
    - "*.company.com"
    - "company.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io

---
# ============================================================
# SPIRE INTERMEDIATE CA via cert-manager (Tier 4)
# Delegates SVID issuance to SPIRE from cert-manager CA
# ============================================================
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spire-intermediate-ca
  namespace: spire
  labels:
    authorizer.io/tier: "4-enterprise"
    authorizer.io/cert-type: "spire-ca"
spec:
  isCA: true
  commonName: "spire-intermediate-ca.company.com"
  secretName: spire-intermediate-ca-secret
  duration: 8760h    # 1 year for intermediate CA
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 384
  issuerRef:
    name: vault-pki-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - cert sign
    - crl sign
