---
# GitHub Actions: Complete Supply Chain Security Pipeline
# Covers: Trivy scan → Cosign sign → Syft SBOM → SLSA L3 provenance
# Reference: https://docs.sigstore.dev/ | https://slsa.dev/spec/v1.0/

name: Secure Build and Attest

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write
  id-token: write          # Required for OIDC/Cosign keyless signing
  security-events: write   # Upload SARIF to GitHub Security
  actions: read            # Required for SLSA generator

jobs:
  # =========================================================
  # Job 1: Security Scanning (Pre-Build)
  # =========================================================
  security-scan:
    name: Pre-Build Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/owasp-top-ten
            p/python
            p/golang
          auditOn: push
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Detect secrets with detect-secrets
        run: |
          pip install detect-secrets
          detect-secrets scan --all-files --exclude-files '\.git' \
            --exclude-files 'poetry.lock' --exclude-files 'package-lock.json' \
            > .secrets.baseline.new
          if [ -f .secrets.baseline ]; then
            detect-secrets audit --diff .secrets.baseline .secrets.baseline.new
          fi

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan IaC with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          scan-ref: .
          format: sarif
          output: trivy-iac.sarif
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Upload IaC SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-iac.sarif

  # =========================================================
  # Job 2: Build Image
  # =========================================================
  build:
    name: Build Container Image
    runs-on: ubuntu-latest
    needs: security-scan
    outputs:
      image: ${{ steps.meta.outputs.tags }}
      digest: ${{ steps.build.outputs.digest }}
      image-uri: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=long,prefix=sha-
          labels: |
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.vendor=MyOrg
            org.opencontainers.image.licenses=Apache-2.0

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: true                    # BuildKit SBOM generation
          provenance: mode=max          # BuildKit provenance (SLSA L2)
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  # =========================================================
  # Job 3: Container Vulnerability Scan
  # =========================================================
  scan-image:
    name: Scan Container Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'

    steps:
      - name: Scan image with Trivy
        id: trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ needs.build.outputs.image-uri }}
          format: sarif
          output: trivy-container.sarif
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true
          scanners: vuln,secret,misconfig
          vuln-type: os,library

      - name: Upload Container SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-container.sarif

  # =========================================================
  # Job 4: Sign Image and Generate SBOM
  # =========================================================
  sign-and-attest:
    name: Sign Image and Attest SBOM
    runs-on: ubuntu-latest
    needs: [build, scan-image]
    if: github.event_name != 'pull_request'

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: v2.4.0

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign container image (keyless OIDC)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes \
            --rekor-url https://rekor.sigstore.dev \
            ${{ needs.build.outputs.image-uri }}

      - name: Generate SBOM with Syft
        run: |
          syft packages ${{ needs.build.outputs.image-uri }} \
            -o spdx-json=sbom.spdx.json \
            -o cyclonedx-json=sbom.cdx.json \
            --source-name ${{ github.repository }} \
            --source-version ${{ github.sha }}

      - name: Attest SBOM (SPDX)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign attest --yes \
            --predicate sbom.spdx.json \
            --type spdxjson \
            ${{ needs.build.outputs.image-uri }}

      - name: Scan SBOM for vulnerabilities
        uses: anchore/scan-action@v4
        with:
          sbom: sbom.cdx.json
          fail-build: true
          severity-cutoff: critical

      - name: Upload SBOMs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: |
            sbom.spdx.json
            sbom.cdx.json
          retention-days: 365          # Keep for compliance evidence

  # =========================================================
  # Job 5: SLSA L3 Provenance
  # =========================================================
  slsa-provenance:
    name: Generate SLSA L3 Provenance
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
      id-token: write
      packages: write
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.0.0
    with:
      image: ${{ needs.build.outputs.image-uri }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  # =========================================================
  # Job 6: Compliance Gate
  # =========================================================
  compliance-gate:
    name: Compliance Verification
    runs-on: ubuntu-latest
    needs: [sign-and-attest, slsa-provenance]
    if: github.event_name != 'pull_request'

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Verify signature
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign verify \
            --certificate-identity-regexp="https://github.com/${{ github.repository }}/.github/workflows/.*@refs/heads/main" \
            --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
            ${{ needs.build.outputs.image-uri }}

      - name: Verify SBOM attestation
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign verify-attestation \
            --type spdxjson \
            --certificate-identity-regexp="https://github.com/${{ github.repository }}/.github/workflows/.*" \
            --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
            ${{ needs.build.outputs.image-uri }}

      - name: Verify SLSA provenance
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign verify-attestation \
            --type slsaprovenance \
            --certificate-identity-regexp="https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/tags/.*" \
            --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
            ${{ needs.build.outputs.image-uri }}

      - name: Generate compliance summary
        run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY
          ## Security Compliance Summary

          | Check | Status |
          |-------|--------|
          | SAST (Semgrep) | ✅ Passed |
          | Secret Detection | ✅ No Secrets Found |
          | IaC Scan | ✅ No CRITICAL/HIGH |
          | Image Vulnerability Scan | ✅ Passed |
          | SBOM Generated | ✅ SPDX + CycloneDX |
          | Image Signed (Cosign) | ✅ Keyless OIDC |
          | SLSA L3 Provenance | ✅ Generated |
          | Compliance Gate | ✅ All checks passed |

          **Image**: \`${{ needs.build.outputs.image-uri }}\`
          **SLSA Level**: 3 (Hardened Build Platform)
          **Signing**: Keyless (Sigstore/Fulcio)
          **Transparency Log**: Rekor
          EOF
