# External Secrets Operator + HashiCorp Vault Integration
# Tier 3+: Automatically syncs secrets from Vault → K8s Secrets

# ClusterSecretStore: cluster-wide Vault connection
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.{{DOMAIN}}"
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      caProvider:
        type: ConfigMap
        name: vault-ca
        namespace: external-secrets
        key: ca.crt
---
# ExternalSecret: sync specific secrets from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{APP_NAME}}-secrets"
  namespace: "{{NAMESPACE}}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: "{{APP_NAME}}-secrets"
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: "{{APP_NAME}}"
          app.kubernetes.io/managed-by: external-secrets
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "services/{{APP_NAME}}/database"
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: "services/{{APP_NAME}}/database"
        property: host
    - secretKey: DB_USER
      remoteRef:
        key: "services/{{APP_NAME}}/database"
        property: username
    - secretKey: API_KEY
      remoteRef:
        key: "services/{{APP_NAME}}/api"
        property: key
---
# ExternalSecret with templating (compose connection string)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{APP_NAME}}-db-url"
  namespace: "{{NAMESPACE}}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: "{{APP_NAME}}-db-url"
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:5432/{{ .database }}?sslmode=require"
  data:
    - secretKey: username
      remoteRef:
        key: "services/{{APP_NAME}}/database"
        property: username
    - secretKey: password
      remoteRef:
        key: "services/{{APP_NAME}}/database"
        property: password
    - secretKey: host
      remoteRef:
        key: "services/{{APP_NAME}}/database"
        property: host
    - secretKey: database
      remoteRef:
        key: "services/{{APP_NAME}}/database"
        property: database
---
# PushSecret: push K8s Secret → Vault (for secret bootstrapping)
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "{{APP_NAME}}-push"
  namespace: "{{NAMESPACE}}"
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: "{{APP_NAME}}-initial-secrets"
  data:
    - match:
        secretKey: DB_PASSWORD
        remoteRef:
          remoteKey: "services/{{APP_NAME}}/database"
          property: password
