# Karpenter Node Autoscaling — Cost-Optimized, Multi-Arch
# Requires: Karpenter v1.1+ installed on EKS

# General-purpose NodePool (spot + on-demand, amd64 + arm64)
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general
spec:
  template:
    metadata:
      labels:
        workload-type: general
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["m7g", "m7i", "m7a", "c7g", "c7i", "c7a"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["medium", "large", "xlarge", "2xlarge"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["{{AZ_1}}", "{{AZ_2}}", "{{AZ_3}}"]
      expireAfter: 720h  # 30 days max node lifetime
  limits:
    cpu: 500
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
    budgets:
      - nodes: "10%"
      - nodes: "0"
        schedule: "0 9 * * 1-5"   # No disruption during business hours
        duration: 8h
  weight: 50  # Prefer this pool (lower weight = higher priority)
---
# High-memory NodePool for databases and caches
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: memory-optimized
spec:
  template:
    metadata:
      labels:
        workload-type: memory-optimized
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]  # No spot for stateful workloads
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["r7g", "r7i", "r7a"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["xlarge", "2xlarge", "4xlarge"]
      taints:
        - key: workload-type
          value: memory-optimized
          effect: NoSchedule
  limits:
    cpu: 200
    memory: 2000Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
  weight: 100
---
# GPU NodePool for ML workloads
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu
spec:
  template:
    metadata:
      labels:
        workload-type: gpu
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu-nodes
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["g5", "g6", "p4d", "p5"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["xlarge", "2xlarge", "4xlarge", "8xlarge"]
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: NoSchedule
  limits:
    cpu: 100
    memory: 500Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 10m
  weight: 100
---
# EC2NodeClass — shared node configuration
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "KarpenterNodeRole-{{CLUSTER_NAME}}"
  amiSelectorTerms:
    - alias: bottlerocket@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{CLUSTER_NAME}}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{CLUSTER_NAME}}"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 100Gi
        iops: 3000
        throughput: 125
        encrypted: true
        deleteOnTermination: true
  tags:
    Environment: "{{ENV}}"
    ManagedBy: karpenter
    Team: platform
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required  # IMDSv2 enforced
---
# EC2NodeClass for GPU nodes
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu-nodes
spec:
  role: "KarpenterNodeRole-{{CLUSTER_NAME}}"
  amiSelectorTerms:
    - alias: al2023@latest  # GPU-compatible AMI
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{CLUSTER_NAME}}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{CLUSTER_NAME}}"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 200Gi
        encrypted: true
  userData: |
    #!/bin/bash
    # Install NVIDIA drivers if not present
    nvidia-smi || yum install -y nvidia-driver
